name: Update Slack Status

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Update Slack Status
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        python - << EOF
        import os
        from status_updater import SlackStatusUpdater

        updater = SlackStatusUpdater(os.getenv('SLACK_TOKEN'))
        updater.update_status()
        EOF